services:
    backend:
        build: .
        volumes:
            - ./src:/code/src
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        command: /bin/sh
        tty: true
